# Лабораторна робота 1. Вступ до машинного навчання. Елементи лінійної алгебри.
**Варіант № 3**

[Посилання на GitHub](https://github.com/unIns1de/MN)




In [2]:
import numpy as np
np.__version__

'2.0.2'

Завдання 1

Створіть одновимірний масив (вектор) з парними числами від 2 до 20 та виведіть його значення.

In [1]:
import numpy as np

arr = np.arange(2, 21, 2)

print("Одновимірний масив з парними числами від 2 до 20:")
print(arr)

Одновимірний масив з парними числами від 2 до 20:
[ 2  4  6  8 10 12 14 16 18 20]


Завдання 2


Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його випадковими
дійсними числами від 0 до 1 та виведіть його значення.

In [3]:
matrix = np.random.rand(3, 3)

print("Матриця 3x3 з випадковими числами від 0 до 1:")
print(matrix)

Матриця 3x3 з випадковими числами від 0 до 1:
[[0.41931655 0.58296553 0.79999453]
 [0.00996776 0.49178178 0.83818276]
 [0.83159074 0.56279801 0.6162742 ]]


Завдання 3


Створіть масив розміром 3x3, заповніть його випадковими натуральними числами від
1 до 20 та виведіть його значення.

In [4]:
matrix = np.random.randint(1, 21, size=(3, 3))

print("Матриця 3x3 з випадковими натуральними числами від 1 до 20:")
print(matrix)

Матриця 3x3 з випадковими натуральними числами від 1 до 20:
[[ 1  3 20]
 [10 11 20]
 [ 6  7  8]]


Завдання 4


Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть мінімальний елемент

In [5]:
matrix = np.random.rand(4, 4)

min_value = np.min(matrix)

print("Матриця 4x4 з випадковими числами від 0 до 1:")
print(matrix)
print("\nМінімальний елемент матриці:", min_value)

Матриця 4x4 з випадковими числами від 0 до 1:
[[0.79951762 0.18204103 0.74738654 0.51556904]
 [0.97082794 0.02223279 0.00297571 0.98946563]
 [0.17549561 0.23788234 0.47765472 0.67270238]
 [0.735122   0.63490648 0.64539833 0.44684904]]

Мінімальний елемент матриці: 0.002975711181756213


Завдання 5


Створіть два одновимірних масиви розміром 7, заповніть їх випадковими цілими
числами в діапазоні від 1 до 15 та виконайте на них поелементні операції додавання,
віднімання та множення.

In [6]:
a = np.random.randint(1, 16, size=7)
b = np.random.randint(1, 16, size=7)

addition = a + b
subtraction = a - b
multiplication = a * b

print("Масив a:", a)
print("Масив b:", b)
print("\nДодавання a + b:", addition)
print("Віднімання a - b:", subtraction)
print("Множення a * b:", multiplication)

Масив a: [ 3  6 14 14  1 13  8]
Масив b: [ 4  4 12  4 11  5  2]

Додавання a + b: [ 7 10 26 18 12 18 10]
Віднімання a - b: [ -1   2   2  10 -10   8   6]
Множення a * b: [ 12  24 168  56  11  65  16]


Завдання 6


Створіть дві матриці 3x3, заповніть їх довільними цілими числами від 3 до 30 та
знайдіть їх добуток.

In [7]:
A = np.random.randint(3, 31, size=(3, 3))
B = np.random.randint(3, 31, size=(3, 3))

product = np.dot(A, B)

print("Матриця A:")
print(A)
print("\nМатриця B:")
print(B)
print("\nДобуток матриць A і B:")
print(product)

Матриця A:
[[15 14 14]
 [15 13 15]
 [18 27 23]]

Матриця B:
[[14 20 22]
 [21 19 18]
 [21 14 27]]

Добуток матриць A і B:
[[ 798  762  960]
 [ 798  757  969]
 [1302 1195 1503]]


Завдання 7


Створіть дві матриці розміром 4x2 та 2x5, заповніть їх випадковими цілими числами
в діапазоні від 1 до 7 та перемножте їх між собою.

In [8]:
A = np.random.randint(1, 8, size=(4, 2))  # 4x2
B = np.random.randint(1, 8, size=(2, 5))  # 2x5

C = np.dot(A, B)

print("Матриця A (4x2):")
print(A)
print("\nМатриця B (2x5):")
print(B)
print("\nДобуток матриць A і B (4x5):")
print(C)

Матриця A (4x2):
[[2 2]
 [2 1]
 [3 2]
 [4 7]]

Матриця B (2x5):
[[3 2 5 2 3]
 [5 5 7 3 3]]

Добуток матриць A і B (4x5):
[[16 14 24 10 12]
 [11  9 17  7  9]
 [19 16 29 12 15]
 [47 43 69 29 33]]


Завдання 8


Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні
від 1 до 8 та знайдіть її обернену матрицю.

In [9]:
A = np.random.randint(1, 9, size=(2, 2))

try:
    A_inv = np.linalg.inv(A)
    print("Матриця A:")
    print(A)
    print("\nОбернена матриця A_inv:")
    print(A_inv)
except np.linalg.LinAlgError:
    print("Матриця не обернена (детермінант = 0):")
    print(A)

Матриця A:
[[4 2]
 [6 2]]

Обернена матриця A_inv:
[[-0.5  0.5]
 [ 1.5 -1. ]]


Завдання 9


Створіть матрицю розміром 2x3, заповніть її випадковими дійсними числами в
діапазоні від 0 до 1 та транспонуйте її.

In [10]:
A = np.random.rand(2, 3)

A_T = A.T

print("Матриця A (2x3):")
print(A)
print("\nТранспонована матриця A_T (3x2):")
print(A_T)

Матриця A (2x3):
[[6.82238083e-01 2.04423121e-01 3.79194112e-01]
 [6.48057364e-01 2.71090097e-04 9.95796956e-01]]

Транспонована матриця A_T (3x2):
[[6.82238083e-01 6.48057364e-01]
 [2.04423121e-01 2.71090097e-04]
 [3.79194112e-01 9.95796956e-01]]


Завдання 10


Створіть матрицю розміром 3x4 та вектор розміром 4 x1, заповніть їх випадковими
цілими числами в діапазоні від 1 до 10 та знайдіть добуток матриці на вектор.

In [11]:
A = np.random.randint(1, 11, size=(3, 4))

v = np.random.randint(1, 11, size=(4, 1))

result = np.dot(A, v)

print("Матриця A (3x4):")
print(A)
print("\nВектор v (4x1):")
print(v)
print("\nДобуток матриці на вектор (3x1):")
print(result)

Матриця A (3x4):
[[ 4  3  7  1]
 [ 9  3  8 10]
 [ 7  2  7  9]]

Вектор v (4x1):
[[2]
 [1]
 [8]
 [6]]

Добуток матриці на вектор (3x1):
[[ 73]
 [145]
 [126]]


Завдання 11


Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в
діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [12]:
A = np.random.rand(2, 3)

v = np.random.randint(1, 11, size=(3, 1))

result = np.dot(A, v)

print("Матриця A (2x3):")
print(A)
print("\nВектор v (3x1):")
print(v)
print("\nДобуток матриці на вектор (2x1):")
print(result)

Матриця A (2x3):
[[0.20284347 0.71846177 0.97053724]
 [0.78325839 0.84626427 0.23564574]]

Вектор v (3x1):
[[6]
 [8]
 [2]]

Добуток матриці на вектор (2x1):
[[ 8.90582949]
 [11.94095597]]


Завдання 12


Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в
діапазоні від 1 до 10 та знайдіть їхню суму.


In [13]:
A = np.random.randint(1, 11, size=(4, 4))
B = np.random.randint(1, 11, size=(4, 4))

sum_matrix = A + B

print("Матриця A:")
print(A)
print("\nМатриця B:")
print(B)
print("\nСума матриць A і B:")
print(sum_matrix)

Матриця A:
[[4 1 2 4]
 [9 8 8 3]
 [9 7 1 8]
 [1 9 5 7]]

Матриця B:
[[ 8  7  5  4]
 [ 6  5  9 10]
 [ 4  6  2  6]
 [ 6  1  7  6]]

Сума матриць A і B:
[[12  8  7  8]
 [15 13 17 13]
 [13 13  3 14]
 [ 7 10 12 13]]


Завдання 13


Створіть дві матриці розміром 4x4, заповніть їх випадковими дійсними числами в
діапазоні від -1 до 1 та знайдіть їх добуток.

In [14]:
A = np.random.uniform(-1, 1, size=(4, 4))
B = np.random.uniform(-1, 1, size=(4, 4))

product = np.dot(A, B)

print("Матриця A:")
print(A)
print("\nМатриця B:")
print(B)
print("\nДобуток матриць A і B:")
print(product)

Матриця A:
[[-0.91741361 -0.15049764  0.93165574  0.94686301]
 [ 0.8841494   0.0156529  -0.84929676  0.50876641]
 [ 0.96053683  0.1652587  -0.96411711 -0.02317327]
 [ 0.35201113  0.63670817 -0.15313971 -0.49185452]]

Матриця B:
[[-0.8108401   0.58921707 -0.09208625 -0.71928953]
 [ 0.91021915  0.35944275  0.30615877  0.31399491]
 [ 0.95570988  0.54184164  0.75732035 -0.74313861]
 [ 0.32645614  0.14479313  0.37151481  0.33928927]]

Добуток матриць A і B:
[[ 1.80639176  0.04725809  1.0957405   0.24154162]
 [-1.34824762  0.14006377 -0.5308012   0.17271972]
 [-1.55740145  0.09961161 -0.77661155  0.06959651]
 [-0.01280683  0.28207648 -0.13618865 -0.10635173]]


Завдання 14


Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -1 до 1 та знайдіть суму елементів матриці.

In [15]:
A = np.random.uniform(-1, 1, size=(3, 3))

sum_elements = np.sum(A)

print("Матриця A (3x3):")
print(A)
print("\nСума елементів матриці:", sum_elements)

Матриця A (3x3):
[[ 0.52928368  0.53956245 -0.6868743 ]
 [ 0.57130735  0.24221883 -0.25858068]
 [ 0.41428406 -0.62019413 -0.38981426]]

Сума елементів матриці: 0.341192999545455


Завдання 15


Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в
діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить суму елементів
кожного рядка матриці.

In [16]:
A = np.random.uniform(-0.5, 0.5, size=(5, 5))

row_sums = np.sum(A, axis=1).reshape(-1, 1)

print("Матриця A (5x5):")
print(A)
print("\nВектор-стовпчик сум елементів кожного рядка:")
print(row_sums)

Матриця A (5x5):
[[ 0.49861296 -0.26735033  0.09067429 -0.11164595  0.04265638]
 [-0.10030123  0.41297635 -0.1216609  -0.29148087  0.45249678]
 [ 0.33741458 -0.30164841 -0.2167852   0.49912589 -0.21253105]
 [-0.11965368  0.33290586  0.40493279 -0.32544763  0.30749335]
 [ 0.29472542 -0.34466034  0.0412548   0.02016848 -0.10345545]]

Вектор-стовпчик сум елементів кожного рядка:
[[ 0.25294735]
 [ 0.35203013]
 [ 0.10557581]
 [ 0.60023069]
 [-0.0919671 ]]
